@BASE_URL = {{HOST}}:{{PORT}}{{BASE_PATH}}

### Create a new user
POST {{BASE_URL}}/user HTTP/1.1
content-type: application/json

{
  "username": "user6",
  "email": "user6@example.com",
  "first_name": "Teste",
  "last_name": "User6",
  "password": "Teste@123.",
  "phone": "43999999999",
  "gender": ["Masculino"]
}

### Update user by ID
PUT {{BASE_URL}}/user?id=6 HTTP/1.1
content-type: application/json

{
  "username": "user7",
  "email": "user7@example.com",
  "first_name": "Teste7",
  "last_name": "User7",
  "password": "Teste@123.",
  "phone": "43777777777",
  "gender": ["Masculino"]
}

### Get user by ID
GET {{BASE_URL}}/user?id=2 HTTP/1.1
content-type: application/json

### List all users
GET {{BASE_URL}}/users HTTP/1.1
content-type: application/json

### delete user by ID
DELETE {{BASE_URL}}/user?id=1 HTTP/1.1
content-type: application/json